
  version: "3.3"
  networks:
    emnutt:

  services:
    emnutt:
      build: .
      ports:
        - "3002:3002"
      restart: unless-stopped
      networks:
        emnutt:
      environment:
        NODE_ENV: docker
        APP_PORT: 3002
        APP_BASE_URL: http://localhost:3002/emNutt
        APP_INSTALLED: "false"
        MACM_BASE_URL: 
        MACM_USERNAME: 
        MACM_PASSWORD: 
        RAPIDPRO_BASE_URL: http://localhost:8000
        RAPIDPRO_TOKEN: kdlsjgklsd
        RAPIDPRO_SYNC_ALL_CONTACTS: "true"
        ELASTIC_BASE_URL: http://elasticsearch:9200
        ELASTIC_USERNAME: 
        ELASTIC_PASSWORD: 
        KIBANA_BASE_URL: 
        KIBANA_USERNAME: 
        KIBANA_PASSWORD: 
        MEDIATOR_API_URL: 
        MEDIATOR_API_USERNAME: root@openhim.org
        MEDIATOR_API_PASSWORD: openhim-password
        MEDIATOR_API_TRUST_SELF_SIGNED: "true"
        MEDIATOR_ROUTER_URL: 
        MEDIATOR_REGISTER: "false"
        MEDIATOR_API_USERNAME: root@openhim.org
        MEDIATOR_API_PASSWORD: openhim-password

    fhir:
      container_name: hapi-fhir
      image: hapiproject/hapi:latest
      networks:
        emnutt:
      ports:
        - '8080:8080'

    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:7.6.2
      environment:
        - node.name=elasticsearch
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=elasticsearch
        - cluster.initial_master_nodes=elasticsearch
        - bootstrap.memory_lock=true
        - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      ulimits:
        memlock:
          soft: -1
          hard: -1
      networks:
        emnutt:
      ports:
        - '9200:9200'

    kibana:
      container_name: kibana
      image: kibana:7.6.2
      networks:
        emnutt:
      ports:
        - '5601:5601'

