
  version: '3.3'
  networks:
    emnutt:

  services:
    emnutt:
      build: .
      ports:
        - '3002:3002'
      restart: unless-stopped
      environment:
        MACM_BASE_URL: http://localhost:8081/scratchpad/fhir
        MACM_USERNAME: 
        MACM_PASSWORD: 
      
